### ISSUE TITLE
Crash from missing Entity.getBlockPos() on 1.16.1

### ISSUE THREAD

**Issue by comp500** [haykam821/Lootstrap#2]
Lootstrap 1.0.0 (built for 1.15.2) claims to support 1.16.1, but the following crash occurs when a player joins, as it tries to call `net.minecraft.class_3222.method_5704()` (`net/minecraft/entity/Entity.getBlockPos()` in 1.15.2 yarn) which doesn't exist in 1.16.1 (or is not properly matched)

Crash log: [crash-2020-08-09_23.53.27-server.txt](https://github.com/haykam821/Lootstrap/files/5048563/crash-2020-08-09_23.53.27-server.txt)

**Comment by haykam821** [comment]
Although it does not support 1.16.1, [version 1.1.0](https://github.com/haykam821/Lootstrap/releases/tag/1.1.0) has been released to support 1.16.x as a whole.
